# permissions for end users to view slpdeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: slpdeployment-viewer-role
rules:
- apiGroups:
  - opa.twdps.io
  resources:
  - slpdeployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - opa.twdps.io
  resources:
  - slpdeployments/status
  verbs:
  - get
