# permissions for end users to edit slpdeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: slpdeployment-editor-role
rules:
- apiGroups:
  - opa.twdps.io
  resources:
  - slpdeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - opa.twdps.io
  resources:
  - slpdeployments/status
  verbs:
  - get
