kind: StatefulSet
apiVersion: apps/v1
metadata:
  name:  {{ .Values.namespace }}-{{ include "slp.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "slp.labels" . | nindent 4 }}
spec:
  replicas: 1
  serviceName:  {{ .Values.namespace }}-{{ include "slp.name" . }}
  selector:
    matchLabels:
      {{- include "slp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        sidecar.istio.io/inject: "false"
        {{- include "slp.selectorLabels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ .Values.namespace }}-{{ include "slp.name" . }}
      containers:
      - name: slp
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
          - "--config-file=/config/{{ include "slp.systemCredentialsSecretName" . }}"
          - "--addr=0.0.0.0:8080"
        livenessProbe:
          httpGet:
            path: /v1/system/alive
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /v1/system/ready
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
        securityContext:
          readOnlyRootFilesystem: true
        volumeMounts:
        - name: {{ .Values.namespace }}-{{ include "slp.name" . }}-credentials-vol
          readOnly: true
          mountPath: /config

        - name: {{ .Values.namespace }}-{{ include "slp.name" . }}-scratch-vol
          mountPath: /scratch
      {{- if .Values.imagePullSecrets -}}
      imagePullSecrets:
      {{- range .Values.imagePullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: {{ .Values.namespace }}-{{ include "slp.name" . }}-credentials-vol
        secret:
          secretName: {{ include "slp.systemCredentialsFilename" . }}
          items:
          - key: das.yaml
            path: das.yaml

  volumeClaimTemplates:
  - metadata:
      name: {{ .Values.namespace }}-{{ include "slp.name" . }}-scratch-vol
      namespace: {{ .Values.namespace }}
      labels:
        slp-pvc: {{ .Values.namespace }}-{{ include "slp.name" . }}-app-pvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      {{- with .Values.storageClassName }}
      storageClassName: {{ .Values.storageClassName }}
      {{- end }}
      resources:
        requests:
          storage: 2Gi